-- Migration: Seed initial prospects data
-- Date: 2026-04-24
-- Description: Add sample prospects for Quito to enable testing

BEGIN;

INSERT INTO prospects (
  nombre,
  dirección,
  teléfono,
  website,
  https,
  facebook_instagram,
  google_rating,
  google_reviews_count,
  tipo_negocio,
  empleados_estimados,
  sri_activo,
  zona,
  score,
  desglose_score,
  fuente,
  data_version
) VALUES
(
  'Cafetería El Punto',
  'Calle Ambato 456, Centro Quito',
  '+593 2 2234567',
  NULL,
  NULL,
  'facebook.com/cafeteriaelpunto',
  4.5,
  32,
  'Cafetería',
  '3-5',
  true,
  'Centro',
  18,
  '{"sin_website": 10, "facebook": 7, "sri_activo": 3, "telefono": 2, "zona_comercial": 2}'::jsonb,
  'manual',
  1
),
(
  'Farmacia Salud+',
  'Av. Amazonas 890, La Carolina',
  '+593 2 3456789',
  'https://farmaciasalud.ec',
  true,
  NULL,
  4.8,
  58,
  'Farmacia',
  '5-10',
  true,
  'La Carolina',
  22,
  '{"website_https": 5, "sri_activo": 3, "telefono": 2, "google_rating": 4, "zona_comercial": 2, "empleados": 2, "reviews": 4}'::jsonb,
  'google_places',
  1
),
(
  'Ferretería López',
  'Calle Venezuela 234, Quito Sur',
  '+593 2 4567890',
  NULL,
  NULL,
  'instagram.com/ferreteria.lopez',
  3.9,
  21,
  'Ferretería',
  '5-20',
  true,
  'Quito Sur',
  16,
  '{"sin_website": 10, "redes_sociales": 2, "sri_activo": 3, "telefono": 2, "zona_comercial": 2}'::jsonb,
  'manual',
  1
),
(
  'Barbería Premium',
  'Calle 10 de Agosto 567, Centro',
  '+593 2 5678901',
  NULL,
  NULL,
  'facebook.com/barberiapremium',
  4.3,
  45,
  'Barbería',
  '1-5',
  true,
  'Centro',
  19,
  '{"sin_website": 10, "facebook": 7, "sri_activo": 3, "telefono": 2, "zona_comercial": 2, "google_rating": 2}'::jsonb,
  'manual',
  1
),
(
  'Restaurante Andino',
  'Calle García Moreno 123, Centro',
  '+593 2 6789012',
  'https://restauranteandino.com',
  true,
  'instagram.com/restauranteandino',
  4.7,
  92,
  'Restaurante',
  '10-20',
  true,
  'Centro',
  20,
  '{"website_https": 5, "sri_activo": 3, "telefono": 2, "google_rating": 4, "zona_comercial": 2, "empleados": 2, "reviews": 2}'::jsonb,
  'google_places',
  1
),
(
  'Tienda de Ropa Estilo',
  'Av. Colón 789, Quito Norte',
  '+593 2 7890123',
  NULL,
  NULL,
  'facebook.com/tienda.estilo',
  4.1,
  28,
  'Tienda de Ropa',
  '3-5',
  true,
  'Quito Norte',
  17,
  '{"sin_website": 10, "facebook": 7, "sri_activo": 3, "telefono": 2, "zona_comercial": 2}'::jsonb,
  'manual',
  1
),
(
  'Taller Mecánico Rápido',
  'Calle Loja 345, Calderón',
  '+593 2 8901234',
  NULL,
  NULL,
  NULL,
  3.8,
  15,
  'Taller Mecánico',
  '5-10',
  true,
  'Calderón',
  12,
  '{"sin_website": 10, "sri_activo": 3, "telefono": 2, "zona_comercial": 2}'::jsonb,
  'manual',
  1
),
(
  'Clínica Dental Sonrisa',
  'Av. 12 de Octubre 654, Cumbayá',
  '+593 2 9012345',
  'https://clinicasonrisa.ec',
  true,
  'instagram.com/clinicasonrisa',
  4.9,
  74,
  'Clínica Dental',
  '5-15',
  true,
  'Cumbayá',
  21,
  '{"website_https": 5, "sri_activo": 3, "telefono": 2, "google_rating": 4, "zona_comercial": 2, "empleados": 2, "reviews": 3}'::jsonb,
  'google_places',
  1
),
(
  'Panadería Tradicional',
  'Calle Sucre 234, Centro',
  '+593 2 1234567',
  NULL,
  NULL,
  'facebook.com/panaderiatradicional',
  4.2,
  36,
  'Panadería',
  '3-5',
  true,
  'Centro',
  18,
  '{"sin_website": 10, "facebook": 7, "sri_activo": 3, "telefono": 2, "zona_comercial": 2}'::jsonb,
  'manual',
  1
),
(
  'Óptica Visión Clara',
  'Av. Patria 890, La Carolina',
  '+593 2 2345678',
  'https://opticavisionclara.com',
  true,
  NULL,
  4.6,
  51,
  'Óptica',
  '3-8',
  true,
  'La Carolina',
  20,
  '{"website_https": 5, "sri_activo": 3, "telefono": 2, "google_rating": 4, "zona_comercial": 2, "empleados": 2, "reviews": 2}'::jsonb,
  'google_places',
  1
);

COMMIT;

-- Down
-- DELETE FROM prospects WHERE fuente = 'manual' AND nombre IN (
--   'Cafetería El Punto',
--   'Barbería Premium',
--   'Tienda de Ropa Estilo',
--   'Taller Mecánico Rápido',
--   'Panadería Tradicional'
-- );
